// Ícones da interface (gerados por scripts/art/icons.mjs).
export const ICONS = {
  coin: require('@/assets/images/ui/coin.png'),
  lock: require('@/assets/images/ui/lock.png'),
  check: require('@/assets/images/ui/check.png'),
  blood: require('@/assets/images/ui/blood.png'),
  back: require('@/assets/images/ui/back.png'),
  next: require('@/assets/images/ui/next.png'),
  pause: require('@/assets/images/ui/pause.png'),
  play: require('@/assets/images/ui/play.png'),
  skull: require('@/assets/images/ui/skull.png'),
  star: require('@/assets/images/ui/star.png'),
  starEmpty: require('@/assets/images/ui/starEmpty.png'),
  gear: require('@/assets/images/ui/gear.png'),
  up: require('@/assets/images/ui/up.png'),
  wrench: require('@/assets/images/ui/wrench.png'),
  shield: require('@/assets/images/ui/shield.png'),
  bullet: require('@/assets/images/ui/bullet.png'),
  book: require('@/assets/images/ui/book.png'),
  trophy: require('@/assets/images/ui/trophy.png'),
  hourglass: require('@/assets/images/ui/hourglass.png'),
  evo: require('@/assets/images/ui/evo.png'),
  radio: require('@/assets/images/ui/radio.png'),
  gem: require('@/assets/images/ui/gem.png'),
  crown: require('@/assets/images/ui/crown.png'),
  bag: require('@/assets/images/ui/bag.png'),
  tv: require('@/assets/images/ui/tv.png'),
};
